QDL.nowrap :Dir

QDL.qdl_alias :Dir, :'self.[]', :'self.glob'

QDL.type :Dir, 'self.chdir', '(?(String or Pathname)) -> 0'
QDL.type :Dir, 'self.chdir', '(?(String or Pathname)) { (?String) -> u } -> u'
QDL.type :Dir, 'self.chroot', '(String) -> 0'
QDL.type :Dir, 'self.delete', '(String) -> 0'
QDL.type :Dir, 'self.entries', '(String, ?Encoding) -> Array<String>'
QDL.type :Dir, 'self.exist?', '(String file) -> %bool'
  # exists? deprecated
QDL.type :Dir, 'self.foreach', '(String dir, ?Encoding) { (String) -> %any } -> nil'
QDL.type :Dir, 'self.foreach', '(String dir, ?Encoding) -> Enumerator<String>'
QDL.type :Dir, 'self.getwd', '() -> String'
QDL.type :Dir, 'self.glob', '(String or Array<String> pattern, ?Fixnum flags) -> Array<String>'
QDL.type :Dir, 'self.glob', '(String or Array<String> pattern, ?Fixnum flags) { (String) -> %any} -> nil'
QDL.type :Dir, 'self.home', '(?String) -> String'
QDL.type :Dir, 'self.mkdir', '(String, ?Integer) -> 0'
QDL.type :Dir, 'self.open', '(String, ?Encoding) -> Dir'
QDL.type :Dir, 'self.open', '(String, ?Encoding) { (Dir) -> u } -> u'
QDL.type :Dir, 'self.pwd', '() -> String'
QDL.type :Dir, 'self.rmdir', '(String) -> 0'
QDL.type :Dir, 'self.unlink', '(String) -> 0'
QDL.type :Dir, :close, '() -> nil'
QDL.type :Dir, :each, '() { (String) -> %any } -> self'
QDL.type :Dir, :each, '() -> Enumerator<String>'
QDL.type :Dir, :fileno, '() -> Integer'
QDL.type :Dir, :initialize, '(String, ?Encoding) -> self'
QDL.type :Dir, :inspect, '() -> String'
QDL.type :Dir, :path, '() -> String or nil'
QDL.type :Dir, :pos, '() -> Integer'
QDL.type :Dir, :pos=, '(Integer) -> Integer'
QDL.type :Dir, :read, '() -> String or nil'
QDL.type :Dir, :rewind, '() -> self'
QDL.type :Dir, :seek, '(Integer) -> self'
QDL.type :Dir, :tell, '() -> Integer'
QDL.type :Dir, :to_path, '() -> String or nil'
