QDL.nowrap :MatchData

QDL.type :MatchData, :==, '(%any) -> %bool'
QDL.type :MatchData, :[], '(Integer i) -> String or nil'
QDL.type :MatchData, :[], '(Integer start, Integer length) -> Array<String>'
QDL.type :MatchData, :[], '(Range<Integer> range) -> Array<String>'
QDL.type :MatchData, :[], '(String or Symbol name) -> String or nil'
QDL.type :MatchData, :begin, '(Integer n) -> Integer'
QDL.type :MatchData, :captures, '() -> Array<String>'
QDL.type :MatchData, :end, '(Integer n) -> Integer'
QDL.type :MatchData, :eql?, '(%any other) -> %bool'
QDL.type :MatchData, :hash, '() -> Integer'
QDL.type :MatchData, :inspect, '() -> String'
QDL.type :MatchData, :length, '() -> Integer'
QDL.type :MatchData, :names, '() -> Array<String>'
QDL.type :MatchData, :offset, '(Integer n) -> Array<Integer>'
QDL.type :MatchData, :post_match, '() -> String'
QDL.type :MatchData, :pre_match, '() -> String'
QDL.type :MatchData, :regexp, '() -> Regexp'
QDL.type :MatchData, :size, '() -> Integer'
QDL.type :MatchData, :string, '() -> String'
QDL.type :MatchData, :to_a, '() -> Array<String>'
QDL.type :MatchData, :to_s, '() -> String'
QDL.type :MatchData, :values_at, '(*Integer indexes) -> Array<String>'
