QDL.nowrap :Module

QDL.type :Module, 'self.constants', '() -> Array<Integer>' # also constants(inherited), but undocumented
QDL.type :Module, 'self.nesting', '() -> Array<Module>'
QDL.type :Module, :initialize, '() -> self'
QDL.type :Module, :initialize, '() { (Module) -> %any } -> self'

QDL.type :Module, :<, '(Module other) -> %bool or nil'
QDL.type :Module, :<=, '(Module other) -> %bool or nil'
QDL.type :Module, :<=>, '(Module other) -> -1 or 0 or 1 or nil'
QDL.type :Module, :==, '(%any other) -> %bool'
QDL.type :Module, :equal?, '(%any other) -> %bool'
QDL.type :Module, :eql?, '(%any other) -> %bool'
QDL.type :Module, :===, '(%any other) -> %bool'
QDL.type :Module, :>, '(Module other) -> %bool or nil'
QDL.type :Module, :>=, '(Module other) -> %bool or nil'
QDL.type :Module, :ancestors, '() -> Array<Module>'
QDL.type :Module, :autoload, '(Symbol module, String filename) -> nil'
QDL.type :Module, :autoload?, '(Symbol name) -> String or nil'
QDL.type :Module, :class_eval, '(?String, ?String filename, ?Integer lineno) -> %any'
QDL.type :Module, :class_eval, '() { () -> x } -> x'
QDL.type :Module, :class_exec, '(*%any args) { (*%any args) -> %any } -> %any'
QDL.type :Module, :class_variable_defined?, '(Symbol or String) -> %bool'
QDL.type :Module, :class_variable_get, '(Symbol or String) -> %any'
QDL.type :Module, :class_variable_set, '(Symbol or String, %any) -> %any'
QDL.type :Module, :class_variables, '(?%bool inherit) -> Array<Symbol>'
QDL.type :Module, :const_defined?, '(Symbol or String, ?%bool inherit) -> %bool'
QDL.type :Module, :const_get, '(Symbol or String, ?%bool inherit) -> Object'
QDL.type :Module, :const_missing, '(Symbol) -> %any'
QDL.type :Module, :const_set, '(Symbol or String, %any) -> %any'
QDL.type :Module, :constants, '(?%bool inherit) -> Array<Symbol>'
QDL.type :Module, :freeze, '() -> self'
QDL.type :Module, :include, '(*Module) -> self'
QDL.type :Module, :include?, '(Module) -> %bool'
QDL.type :Module, :included_modules, '() -> Array<Module>'
QDL.qdl_alias :Module, :inspect, :to_s
QDL.type :Module, :instance_method, '(Symbol) -> UnboundMethod'
QDL.type :Module, :instance_methods, '(?%bool include_super) -> Array<Symbol>'
QDL.type :Module, :method_defined?, '(Symbol or String) -> %bool'
QDL.type :Module, :module_eval, '(String, ?String filename, ?Integer lineno) -> %any' # matches rdoc example but not QDL.type
QDL.type :Module, :module_exec, '(*%any args) { (*%any) -> %any } -> %any'
QDL.type :Module, :name, '() -> String'
QDL.type :Module, :prepend, '(*Module) -> self'
QDL.type :Module, :private_class_method, '(*(Symbol or String)) -> self'
QDL.type :Module, :private_constant, '(*Symbol) -> self'
QDL.type :Module, :private_instance_methods, '(?%bool include_super) -> Array<Symbol>'
QDL.type :Module, :private_method_defined?, '(Symbol or String) -> %bool'
QDL.type :Module, :protected_instance_methods, '(?%bool include_super) -> Array<Symbol>'
QDL.type :Module, :protected_method_defined?, '(Symbol or String) -> %bool'
QDL.type :Module, :public_class_method, '(*(Symbol or String)) -> self'
QDL.type :Module, :public_constant, '(*Symbol) -> self'
QDL.type :Module, :public_instance_method, '(Symbol) -> UnboundMethod'
QDL.type :Module, :public_instance_methods, '(?%bool include_super) -> Array<Symbol>'
QDL.type :Module, :public_method_defined?, '(Symbol or String) -> %bool'
QDL.type :Module, :remove_class_variable, '(Symbol) -> %any'
QDL.type :Module, :singleton_class?, '() -> %bool'
QDL.type :Module, :to_s, '() -> String'
# private methods below here
QDL.type :Module, :alias_method, '(Symbol or String new_name, Symbol or String old_name) -> self'
QDL.type :Module, :append_features, '(Module) -> self'
QDL.qdl_alias :Module, :attr, :attr_reader
QDL.type :Module, :attr_accessor, '(*(Symbol or String)) -> nil'
QDL.type :Module, :attr_reader, '(*(Symbol or String)) -> nil'
QDL.type :Module, :attr_writer, '(*(Symbol or String)) -> nil'
QDL.type :Module, :define_method, '(Symbol, Method) -> Symbol'
QDL.type :Module, :define_method, '(Symbol) { (*%any) -> %any } -> Symbol'
QDL.type :Module, :extend_object, '(%any) -> %any'
QDL.type :Module, :extended, '(Module othermod) -> %any'
QDL.type :Module, :included, '(Module othermod) -> %any'
QDL.type :Module, :method_added, '(Symbol method_name) -> %any'
QDL.type :Module, :method_removed, '(Symbol method_name) -> %any'
QDL.type :Module, :module_function, '(*(Symbol or String)) -> self'
QDL.type :Module, :prepend_features, '(Module) -> self'
QDL.type :Module, :prepended, '(Module othermod) -> %any'
QDL.type :Module, :private, '(*(Symbol or String)) -> self'
QDL.type :Module, :protected, '(*(Symbol or String)) -> self'
QDL.type :Module, :public, '(*(Symbol or String)) -> self'
QDL.type :Module, :refine, '(Class) { (%any) -> %any } -> self' # ??
QDL.type :Module, :remove_const, '(Symbol) -> %any'
QDL.type :Module, :remove_method, '(Symbol or String) -> self'
QDL.type :Module, :undef_method, '(Symbol or String) -> self'
QDL.type :Module, :using, '(Module) -> self'
