QDL.nowrap :Time

QDL.type :Time, 'self.at', '(Numeric, ?Numeric) -> ``QDL::Type::NominalType.new(trec.val)``'
QDL.type :Time, 'self.at', '(Time) -> Time'
QDL.type :Time, 'self.at', '(Numeric seconds_with_frac) -> Time'
QDL.type :Time, 'self.at', '(Numeric seconds, Numeric microseconds_with_frac) -> Time'
QDL.type :Time, 'self.gm', '(Integer year, ?(Integer or String) month, ?Integer day, ?Integer hour, ?Integer min, ?Numeric sec, ?Numeric usec_with_frac) -> Time'
QDL.type :Time, 'self.local', '(Integer year, ?(Integer or String) month, ?Integer day, ?Integer hour, ?Integer min, ?Numeric sec, ?Numeric usec_with_frac) -> Time'
QDL.qdl_alias :Time, 'self.mktime', 'self.local'
QDL.type :Time, :initialize, '(?Integer year, ?(Integer or String) month, ?Integer day, ?Integer hour, ?Integer min, ?Numeric sec, ?Numeric usec_with_frac) -> self'
QDL.type :Time, 'self.now', '() -> Time'
QDL.type :Time, 'self.utc', '(Integer year, ?(Integer or String) month, ?Integer day, ?Integer hour, ?Integer min, ?Numeric sec, ?Numeric usec_with_frac) -> Time'

QDL.type :Time, :+, '(Numeric) -> Time'
QDL.type :Time, :-, '(Time) -> Float'
QDL.type :Time, :-, '(Numeric) -> Time'
QDL.type :Time, :<=>, '(Time or DateTime) -> -1 or 0 or 1 or nil'
QDL.type :Time, :asctime, '() -> String'
QDL.type :Time, :ctime, '() -> String'
QDL.type :Time, :day, '() -> Integer'
QDL.type :Time, :dst?, '() -> %bool'
QDL.type :Time, :eql?, '(%any) -> %bool'
QDL.type :Time, :friday?, '() -> %bool'
QDL.type :Time, :getgm, '() -> Time'
QDL.type :Time, :getlocal, '(?Integer utc_offset) -> Time'
QDL.type :Time, :getutc, '() -> Time'
QDL.type :Time, :gmt?, '() -> %bool'
QDL.type :Time, :gmt_offset, '() -> Integer'
QDL.type :Time, :gmtime, '() -> self'
QDL.qdl_alias :Time, :gmtoff, :gmt_offset
QDL.type :Time, :hash, '() -> Integer'
QDL.type :Time, :hour, '() -> Integer'
QDL.type :Time, :inspect, '() -> String'
QDL.type :Time, :isdst, '() -> %bool'
QDL.type :Time, :localtime, '(?(String or Integer)) -> self'
QDL.type :Time, :mday, '() -> Integer'
QDL.type :Time, :min, '() -> Integer'
QDL.type :Time, :mon, '() -> Integer'
QDL.type :Time, :monday?, '() -> %bool'
QDL.qdl_alias :Time, :month, :mon
QDL.type :Time, :nsec, '() -> Integer'
QDL.type :Time, :round, '(Integer) -> Time'
QDL.type :Time, :saturday?, '() -> %bool'
QDL.type :Time, :sec, '() -> Integer'
QDL.type :Time, :strftime, '(String) -> String'
QDL.type :Time, :subsec, '() -> Integer or Rational'
QDL.type :Time, :succ, '() -> Time'
QDL.type :Time, :sunday?, '() -> %bool'
QDL.type :Time, :thursday?, '() -> %bool'
QDL.type :Time, :to_a, '() -> [Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, %bool, String]'
QDL.type :Time, :to_f, '() -> Float'
QDL.type :Time, :to_i, '() -> Integer'
QDL.type :Time, :to_r, '() -> Rational'
QDL.type :Time, :to_s, '() -> String'
QDL.type :Time, :tuesday?, '() -> %bool'
QDL.type :Time, :tv_nsec, '() -> Numeric'
QDL.type :Time, :tv_sec, '() -> Numeric'
QDL.type :Time, :tv_usec, '() -> Numeric'
QDL.type :Time, :usec, '() -> Numeric'
QDL.type :Time, :utc, '() -> self'
QDL.type :Time, :utc?, '() -> %bool'
QDL.type :Time, :utc_offset, '() -> Integer'
QDL.type :Time, :wday, '() -> Integer'
QDL.type :Time, :wednesday?, '() -> %bool'
QDL.type :Time, :yday, '() -> Integer'
QDL.type :Time, :year, '() -> Integer'
QDL.type :Time, :zone, '() -> String'
