QDL.nowrap :'ActiveSupport::TimeWithZone'
QDL.type :'ActiveSupport::TimeWithZone', :beginning_of_day, '() -> ActiveSupport::TimeWithZone'
QDL.type :'ActiveSupport::TimeWithZone', :end_of_day, '() -> ActiveSupport::TimeWithZone'
QDL.type :'ActiveSupport::TimeWithZone', :beginning_of_week, '() -> ActiveSupport::TimeWithZone'
QDL.type :'ActiveSupport::TimeWithZone', :end_of_week, '() -> ActiveSupport::TimeWithZone'
QDL.type :'ActiveSupport::TimeWithZone', :to_date, '() -> Date'
QDL.type :'ActiveSupport::TimeWithZone', :strftime, '(String) -> String'
QDL.type :'ActiveSupport::TimeWithZone', :+, '(ActiveSupport::Duration) -> ActiveSupport::TimeWithZone'
QDL.type :'ActiveSupport::TimeWithZone', :-, '(ActiveSupport::Duration) -> ActiveSupport::TimeWithZone'
QDL.type :'ActiveSupport::TimeWithZone', :<, '(ActiveSupport::TimeWithZone or Time) -> %bool'
QDL.type :'ActiveSupport::TimeWithZone', :>, '(ActiveSupport::TimeWithZone or Time) -> %bool'
QDL.type :'ActiveSupport::TimeWithZone', :<=, '(ActiveSupport::TimeWithZone or Time) -> %bool'
QDL.type :'ActiveSupport::TimeWithZone', :>=, '(ActiveSupport::TimeWithZone or Time) -> %bool'
